import React, { useMemo, useState } from 'react';
import { ArrowRight, BadgeCheck, Building2, MapPin, Search, SlidersHorizontal } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import type { Project } from '../../types';

export const ProjectsListingsView: React.FC = () => {
  const { projects, navigateToProjectDetail } = useApp();
  const [query, setQuery] = useState('');
  const [locality, setLocality] = useState('');
  const [status, setStatus] = useState('');
  const [sort, setSort] = useState<'recommended'|'price-asc'|'price-desc'>('recommended');
  const [featuredOnly, setFeaturedOnly] = useState(false);
  const localities = Array.from(new Set(projects.map(p => p.locality).filter(Boolean)));
  const filtered = useMemo(() => projects.filter(p => {
    const q=query.toLowerCase();
    return (!q || `${p.name} ${p.builderName} ${p.locality} ${p.description}`.toLowerCase().includes(q)) && (!locality || p.locality===locality) && (!status || p.status===status) && (!featuredOnly || p.featured);
  }).sort((a,b)=> sort==='price-asc'?a.minPrice-b.minPrice:sort==='price-desc'?b.minPrice-a.minPrice:0), [projects,query,locality,status,sort,featuredOnly]);
  return <div className="min-h-screen bg-[#F7F8FA] py-7 sm:py-9"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#214E9B]">Auricity Projects</span><span className="text-xs font-bold text-slate-500">{filtered.length} projects</span></div><h1 className="mt-3 text-2xl font-black tracking-tight text-slate-950 sm:text-4xl">RERA Registered Projects in Sambhajinagar</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Explore projects with pricing, configurations, RERA details, amenities, possession timelines and developer information.</p></div><div className="flex items-center gap-2"><select value={sort} onChange={e=>setSort(e.target.value as any)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-black"><option value="recommended">Recommended</option><option value="price-asc">Price: Low to High</option><option value="price-desc">Price: High to Low</option></select></div></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="relative lg:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project, builder or locality" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-10 pr-3 text-xs font-medium outline-none focus:border-[#214E9B]"/></div><select value={locality} onChange={e=>setLocality(e.target.value)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-xs font-bold"><option value="">All Localities</option>{localities.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-xs font-bold"><option value="">All Statuses</option>{Array.from(new Set(projects.map(p=>p.status))).map(x=><option key={x}>{x}</option>)}</select></div><label className="mt-4 inline-flex cursor-pointer items-center gap-2 text-xs font-bold text-slate-700"><input type="checkbox" checked={featuredOnly} onChange={e=>setFeaturedOnly(e.target.checked)} className="h-4 w-4 accent-[#214E9B]"/><SlidersHorizontal className="h-4 w-4 text-[#214E9B]"/> Show featured projects only</label>
    </div>
    <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><ProjectCard key={p.id} project={p} onOpen={()=>navigateToProjectDetail(p.id)}/>)}</div>{!filtered.length&&<div className="mt-6 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><Building2 className="mx-auto h-9 w-9 text-slate-300"/><h2 className="mt-4 font-black">No projects match these filters</h2><p className="mt-2 text-sm text-slate-500">Try another locality, status or search term.</p></div>}
  </div></div>;
};

const ProjectCard: React.FC<{project:Project;onOpen:()=>void}> = ({project,onOpen}) => { const image=project.images?.[0]||project.image||project.bannerImage||'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'; return <article className="group overflow-hidden rounded-[1.7rem] border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[16/10] overflow-hidden bg-slate-100"><img src={image} alt={project.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy"/><div className="absolute inset-x-0 top-0 flex items-center justify-between p-3"><span className="rounded-full bg-white/95 px-2.5 py-1 text-[10px] font-black text-[#102B59]">{project.status}</span>{project.featured&&<span className="rounded-full bg-[#D9B45B] px-2.5 py-1 text-[10px] font-black text-[#102B59]">Featured</span>}</div></div><div className="p-5"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-[#B68A32]"><BadgeCheck className="h-3.5 w-3.5"/> RERA {project.reraNumber || project.reraId || 'Details available'}</div><h2 className="mt-2 line-clamp-2 text-lg font-black text-slate-950">{project.name}</h2><p className="mt-1 text-xs font-bold text-slate-500">{project.builderName || project.developer}</p><div className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-600"><MapPin className="h-4 w-4 text-[#214E9B]"/><span className="truncate">{project.locality || project.location}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">Starting</p><p className="mt-1 text-sm font-black">₹{(project.minPrice/100000).toFixed(1)} L</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">Configs</p><p className="mt-1 truncate text-xs font-black">{project.configurations?.join(', ') || '—'}</p></div></div><button onClick={onOpen} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#102B59] px-4 py-3 text-xs font-black text-white">View Project <ArrowRight className="h-4 w-4"/></button></div></article> }
