import React, { useMemo, useState } from 'react';
import { useApp } from '../../context/AppContext';
import { Archive, CheckCircle2, Eye, FileText, Mail, MapPin, MessageCircle, Pencil, PhoneCall, Save, Search, Settings, Trash2, X } from 'lucide-react';

const tabs = ['Overview','Contact Page CMS','Contact Messages'] as const;
type Tab = typeof tabs[number];

export const ContactManager: React.FC = () => {
  const { contactPageConfig:c, updateContactPageConfig, contactMessages, updateContactMessage, deleteContactMessage, showToast, setActiveView } = useApp();
  const [tab,setTab]=useState<Tab>('Overview'); const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [type,setType]=useState('all'); const [selected,setSelected]=useState<string|null>(null);
  const filtered=useMemo(()=>contactMessages.filter(m=>(status==='all'||m.status===status)&&(type==='all'||m.inquiryType===type)&&`${m.name} ${m.email} ${m.subject} ${m.message}`.toLowerCase().includes(search.toLowerCase())),[contactMessages,status,type,search]);
  const save=()=>showToast('Contact page configuration saved.','success');
  const setCfg=(patch:any)=>updateContactPageConfig(patch);
  const updateFaq=(i:number,patch:any)=>setCfg({faqs:c.faqs.map((f,idx)=>idx===i?{...f,...patch}:f)});
  return <div className="space-y-6">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-blue-700">Website CMS</p><h2 className="text-2xl font-black text-slate-900">Contact Management</h2><p className="text-sm text-slate-500 mt-1">Manage the public Contact page and private contact messages.</p></div><div className="flex gap-2"><button onClick={()=>setActiveView('contact')} className="px-4 py-2.5 rounded-xl bg-slate-100 text-slate-800 font-black text-xs"><Eye className="inline w-4 h-4 mr-1"/> Preview</button></div></div>
    <div className="flex gap-2 overflow-x-auto border-b border-slate-200">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-3 text-xs font-black whitespace-nowrap border-b-2 ${tab===x?'border-blue-700 text-blue-700':'border-transparent text-slate-500'}`}>{x}</button>)}</div>
    {tab==='Overview'&&<div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[['Total Messages',contactMessages.length],['New',contactMessages.filter(x=>x.status==='new').length],['In Progress',contactMessages.filter(x=>x.status==='in_progress').length],['Resolved',contactMessages.filter(x=>x.status==='resolved').length]].map(([label,n])=><div key={label as string} className="p-5 rounded-2xl bg-white border border-slate-200"><p className="text-[10px] uppercase font-black text-slate-400">{label}</p><p className="text-3xl font-black text-slate-900 mt-1">{n as number}</p></div>)}</div>}
    {tab==='Contact Page CMS'&&<div className="space-y-6">
      <Section title="Hero"><Text label="Heading" value={c.heroTitle} onChange={v=>setCfg({heroTitle:v})}/><Text label="Subtitle" value={c.heroSubtitle} onChange={v=>setCfg({heroSubtitle:v})}/><Text label="Hero image URL" value={c.heroImage||''} onChange={v=>setCfg({heroImage:v})}/></Section>
      <Section title="Contact Information"><Text label="Email" value={c.email} onChange={v=>setCfg({email:v})}/><Text label="Phone" value={c.phone} onChange={v=>setCfg({phone:v})}/><Text label="Address" value={c.address} onChange={v=>setCfg({address:v})}/><Text label="Working hours" value={c.workingHours} onChange={v=>setCfg({workingHours:v})}/></Section>
      <Section title="Contact Form"><Text label="Form title" value={c.formTitle} onChange={v=>setCfg({formTitle:v})}/><Text label="Form subtitle" value={c.formSubtitle} onChange={v=>setCfg({formSubtitle:v})}/><Text label="Button text" value={c.formButtonText} onChange={v=>setCfg({formButtonText:v})}/><div><label className="text-xs font-black text-slate-700">Inquiry categories (one per line)</label><textarea value={c.inquiryTypes.join('\n')} onChange={e=>setCfg({inquiryTypes:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})} rows={7} className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm"/></div></Section>
      <Section title="Quick Contact"><div className="grid sm:grid-cols-2 gap-4">{c.quickActions.map((a,i)=><div key={a.id} className="p-4 rounded-xl border border-slate-200"><div className="flex items-center justify-between"><b className="text-sm">{a.label}</b><input type="checkbox" checked={a.enabled} onChange={e=>setCfg({quickActions:c.quickActions.map((x,idx)=>idx===i?{...x,enabled:e.target.checked}:x)})}/></div><input value={a.value||''} onChange={e=>setCfg({quickActions:c.quickActions.map((x,idx)=>idx===i?{...x,value:e.target.value}:x)})} placeholder="Destination / detail" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2 text-xs"/></div>)}</div></Section>
      <Section title="Map"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={c.mapEnabled} onChange={e=>setCfg({mapEnabled:e.target.checked})}/> Enable map</label><Text label="Location name" value={c.mapLocationName} onChange={v=>setCfg({mapLocationName:v})}/><Text label="Address" value={c.mapAddress} onChange={v=>setCfg({mapAddress:v})}/><Text label="Map embed URL" value={c.mapEmbedUrl} onChange={v=>setCfg({mapEmbedUrl:v})}/></Section>
      <Section title="FAQs"><div className="space-y-3">{c.faqs.map((f,i)=><div key={i} className="p-4 rounded-xl border border-slate-200 grid gap-2"><input value={f.question} onChange={e=>updateFaq(i,{question:e.target.value})} className="rounded-lg border px-3 py-2 text-sm font-bold"/><textarea value={f.answer} onChange={e=>updateFaq(i,{answer:e.target.value})} rows={2} className="rounded-lg border px-3 py-2 text-sm"/><div className="flex items-center gap-3 text-xs"><label><input type="checkbox" checked={f.visible} onChange={e=>updateFaq(i,{visible:e.target.checked})}/> Visible</label><button onClick={()=>setCfg({faqs:c.faqs.filter((_,idx)=>idx!==i)})} className="text-red-600 font-bold">Delete</button></div></div>)}</div><button onClick={()=>setCfg({faqs:[...c.faqs,{question:'New question',answer:'New answer',visible:true,order:c.faqs.length+1}]})} className="mt-3 px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-black">Add FAQ</button></Section>
      <Section title="Bottom CTA"><Text label="Heading" value={c.bottomCtaTitle} onChange={v=>setCfg({bottomCtaTitle:v})}/><Text label="Description" value={c.bottomCtaDescription} onChange={v=>setCfg({bottomCtaDescription:v})}/><Text label="Button text" value={c.bottomCtaButtonText} onChange={v=>setCfg({bottomCtaButtonText:v})}/><Text label="Button link" value={c.bottomCtaButtonLink} onChange={v=>setCfg({bottomCtaButtonLink:v})}/></Section>
      <button onClick={save} className="px-6 py-3 rounded-xl bg-[#0b2b5b] text-white font-black text-sm"><Save className="inline w-4 h-4 mr-2"/>Save Contact Page</button>
    </div>}
    {tab==='Contact Messages'&&<div className="space-y-4"><div className="grid md:grid-cols-[1fr_180px_220px] gap-3"><div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, subject…" className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-slate-200"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-3 text-sm"><option value="all">All statuses</option><option value="new">New</option><option value="read">Read</option><option value="in_progress">In Progress</option><option value="resolved">Resolved</option><option value="archived">Archived</option></select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border px-3 text-sm"><option value="all">All inquiry types</option>{c.inquiryTypes.map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto bg-white rounded-2xl border border-slate-200"><table className="w-full text-left text-xs"><thead><tr className="border-b bg-slate-50"><th className="p-3">Name</th><th className="p-3">Subject</th><th className="p-3">Type</th><th className="p-3">Status</th><th className="p-3">Submitted</th><th className="p-3">Action</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id} className="border-b last:border-0"><td className="p-3 font-bold">{m.name}<div className="text-slate-400 font-normal">{m.email}</div></td><td className="p-3">{m.subject}</td><td className="p-3">{m.inquiryType}</td><td className="p-3"><select value={m.status} onChange={e=>updateContactMessage(m.id,{status:e.target.value as any})} className="rounded-lg border px-2 py-1"><option value="new">New</option><option value="read">Read</option><option value="in_progress">In Progress</option><option value="resolved">Resolved</option><option value="archived">Archived</option></select></td><td className="p-3 text-slate-500">{new Date(m.createdAt).toLocaleString()}</td><td className="p-3"><button onClick={()=>setSelected(m.id)} className="px-2.5 py-1.5 rounded-lg bg-slate-100 font-bold mr-1"><Eye className="w-3.5 h-3.5 inline"/></button><button onClick={()=>deleteContactMessage(m.id)} className="px-2.5 py-1.5 rounded-lg bg-red-50 text-red-600 font-bold"><Trash2 className="w-3.5 h-3.5 inline"/></button></td></tr>)}</tbody></table></div></div>}
    {selected&&<MessageDrawer id={selected} close={()=>setSelected(null)}/>} 
  </div>;
};
const Section:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><div className="bg-white rounded-2xl border border-slate-200 p-5 space-y-4"><h3 className="font-black text-lg text-slate-900">{title}</h3>{children}</div>;
const Text:React.FC<{label:string;value:string;onChange:(v:string)=>void}>=({label,value,onChange})=><div><label className="text-xs font-black text-slate-700">{label}</label><input value={value||''} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div>;
const MessageDrawer:React.FC<{id:string;close:()=>void}>=({id,close})=>{const {contactMessages,updateContactMessage}=useApp();const m=contactMessages.find(x=>x.id===id);if(!m)return null;return <div className="fixed inset-0 z-[80] bg-slate-950/50 flex justify-end" onClick={close}><div onClick={e=>e.stopPropagation()} className="w-full max-w-xl bg-white h-full overflow-y-auto p-6"><div className="flex justify-between items-center"><h3 className="text-xl font-black">Message Details</h3><button onClick={close}><X/></button></div><div className="mt-6 space-y-4 text-sm"><p><b>Name:</b> {m.name}</p><p><b>Email:</b> {m.email}</p><p><b>Phone:</b> {m.phone||'—'}</p><p><b>Subject:</b> {m.subject}</p><p><b>Inquiry Type:</b> {m.inquiryType}</p><p><b>Submitted:</b> {new Date(m.createdAt).toLocaleString()}</p><div><b>Message</b><div className="mt-2 p-4 rounded-xl bg-slate-50 border whitespace-pre-wrap">{m.message}</div></div><div><label className="font-bold">Admin Notes</label><textarea value={m.adminNotes||''} onChange={e=>updateContactMessage(m.id,{adminNotes:e.target.value})} rows={4} className="mt-2 w-full rounded-xl border p-3"/></div><div className="grid grid-cols-2 gap-2">{(['read','in_progress','resolved','archived'] as const).map(s=><button key={s} onClick={()=>updateContactMessage(m.id,{status:s})} className="px-3 py-2 rounded-xl bg-slate-100 font-bold capitalize">Mark {s.replace('_',' ')}</button>)}</div></div></div></div>};
